import Head from "next/head";
import { GetStaticProps, GetStaticPaths } from "next";

export const getStaticProps: GetStaticProps = async () => {
  const now = new Date().toISOString();
  console.log("getStaticProps", now);
  return {
    props: {
      now,
    },
  };
};

const About = ({ now }: { now: string }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>About Page, timestamp: {now}.</h1>
      </main>
    </div>
  );
};

export default About;
